Repository Finschia/wasmd, pull requests merged in 2023-08, with the labels that each got.

#77 fix: use ctx cache in msg server integration test
  CHANGELOG.md
  x/wasm/keeper/msg_server_integration_test.go
Labels: bug

#92 docs: modify links in x/wasmplus README.md
  CHANGELOG.md
  x/wasmplus/README.md
Labels: documentation

#84 feat: Introduce AcceptListStargateQuerier
  CHANGELOG.md
  x/wasm/keeper/options.go
  x/wasm/keeper/query_plugins.go
  x/wasm/keeper/query_plugins_test.go
  x/wasm/keeper/reflect_test.go
Labels: enhancement
